function compileMex(varargin)

if ~exist('../private','dir')
  mkdir('../private');
end

if nargin==0
  mex -v -largeArrayDims -O ...
    -DNDEBUG -DREAL=float -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O3 -funroll-loops" ...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxPccXx.c ...
    ../../corr/src/pcc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    -outdir ../private ...
    -output mxPccXxFlt
  
  mex -v -largeArrayDims -O ...
    -DNDEBUG -DREAL=double -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O3 -funroll-loops"...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxPccXx.c ...
    ../../corr/src/pcc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    -outdir ../private ...
    -output mxPccXxDbl
  
  mex -v -largeArrayDims -O ...
    -DNDEBUG -DREAL=float -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O3" ...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxTetraccXx.c ...
    ../../corr/src/tetracc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    ../../corr/src/binarize.c ...
    -outdir ../private ...
    -output mxTetraccXxFlt
  mex -v -largeArrayDims -O ...
    -DNDEBUG -DREAL=double -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O3" ...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxTetraccXx.c ...
    ../../corr/src/tetracc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    ../../corr/src/binarize.c ...
    -outdir ../private ...
    -output mxTetraccXxDbl
  
elseif(strcmp(varargin{1},'debug'))
  
    mex -g -v -largeArrayDims -O ...
    -DREAL=float -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O2" ...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxPccXx.c ...
    ../../corr/src/pcc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    -outdir ../private ...
    -output mxPccXxFlt
  
  mex -g -v -largeArrayDims -O ...
    -DREAL=double -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O2"...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxPccXx.c ...
    ../../corr/src/pcc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    -outdir ../private ...
    -output mxPccXxDbl
  
  mex -g -v -largeArrayDims -O ...
    -DREAL=float -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O2" ...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxTetraccXx.c ...
    ../../corr/src/tetracc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    ../../corr/src/binarize.c ...
    -outdir ../private ...
    -output mxTetraccXxFlt
  mex -g -v -largeArrayDims -O ...
    -DREAL=double -DMATLAB ...
    CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
    -fPIC -std=c99 -march=native" ...
    COPTIMFLAGS="-O2" ...
    -lm ...
    -I../../corr/src ...
    -I../../cpuinfo/src ...
    mxTetraccXx.c ...
    ../../corr/src/tetracc.c ...
    ../../cpuinfo/src/cpuinfo.c ...
    ../../corr/src/binarize.c ...
    -outdir ../private ...
    -output mxTetraccXxDbl
  
else
  error('Unexpected input argument.');
end

end
