%-----------------------------------------------------------------------------
% File    : compileMex.m
% Contents: build MEX-files
%           NB: This file is obsolete. Use the makefile instead.
% Author  : Kristian Loewe
%-----------------------------------------------------------------------------

if ~exist('../private','dir'); mkdir('../private'); end

%% pcc xx (flt)
mex -v -largeArrayDims -O ...
  -DNDEBUG -DREAL=float ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  COPTIMFLAGS="-O3 -funroll-loops" ...
  -lm -lpthread ...
  -I../../corr/src ...
  -I../../cpuinfo/src ...
  mxPccXx.c ...
  ../../corr/src/pcc.c ...
  ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private ...
  -output mxPccXxFlt

%% pcc xx (dbl)
mex -v -largeArrayDims -O ...
  -DNDEBUG -DREAL=double ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  COPTIMFLAGS="-O3 -funroll-loops"...
  -lm -lpthread ...
  -I../../corr/src ...
  -I../../cpuinfo/src ...
  mxPccXx.c ...
  ../../corr/src/pcc.c ...
  ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private ...
  -output mxPccXxDbl

%% tetracc xx (flt)
mex -v -largeArrayDims -O ...
  -DNDEBUG -DREAL=float ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  COPTIMFLAGS="-O3" ...
  -lm -lpthread ...
  -I../../corr/src ...
  -I../../cpuinfo/src ...
  mxTetraccXx.c ...
  ../../corr/src/tetracc.c ...
  ../../corr/src/binarize.c ...
  ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private ...
  -output mxTetraccXxFlt

%% tetracc xx (dbl)
mex -v -largeArrayDims -O ...
  -DNDEBUG -DREAL=double ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  COPTIMFLAGS="-O3" ...
  -lm -lpthread ...
  -I../../corr/src ...
  -I../../cpuinfo/src ...
  mxTetraccXx.c ...
  ../../corr/src/tetracc.c ...
  ../../corr/src/binarize.c ...
  ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private ...
  -output mxTetraccXxDbl
